name: DiscordCraft
version: ${version}
main: com.pablobh.discordcraft.spigot.DiscordCraftPlugin
api-version: 1.20
author: pablobh2147
description: Discord integration plugin for Minecraft servers
load: STARTUP
website: https://github.com/pablobh2147/discordcraft
